# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babar_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nickname',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
