# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babar_server', '0002_auto_20160225_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
    ]
