# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 09:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babar_server', '0003_auto_20160228_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='year',
            field=models.PositiveSmallIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000)]),
            preserve_default=False,
        ),
    ]
