# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 21:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('babar_twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 9, 21, 51, 22, 640142, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
