# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babar_twitter', '0002_tweet_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='message',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
